### ISSUE TITLE
Make visualizer more compatible with long value names on Windows.

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct_visualizer#14]
I have the following KSY:

    seq:
      - id:       control_info_check_hdr_none
        contents: [0x78]
        if:       is_header_none
        doc:      TODO docs

leading to the following error message:

> [.] control_info_check_hdr_short = C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/node.rb:114:in `draw': undefined method `+' for nil:NilClass (NoMethodError)
        from C:/Program Files (x86)/kaitai_struct/visualizer/lib/kaitai/struct/visualizer/tree.rb:190:in `block in draw_rec'

I can workaround the problem simply be shortening the name. But 1. it took me a while to understand the problem, because I have longer (instance) names in the same type without this problem, and 2. I think the visualizer could do this on it's own as well. It could either simply reduce the whole string it wanted to show to the absolute maximum so that the `...` can still be added or reduce the name a bit and add a bit of the value.

> [.] control_info_check_hdr_sh...
vs.
> [.] control_info_c... = 78

Would only be great if it wouldn't crash. :-) Thanks!

**Comment by ams-tschoening** [comment]
The crash been fixed in the meantime with the following commit: https://github.com/kaitai-io/kaitai_struct_visualizer/commit/21744e03ef973ebacdbae3cd026eecb95de36346

![Clipboard01](https://user-images.githubusercontent.com/6223655/55649341-0a174280-57e3-11e9-8ea1-2fa01d484c57.png)

**Comment by ams-tschoening** [comment]
I did some research on adding resize support for the Windows console and would like to document the most interesting findings:

https://stackoverflow.com/a/34208406/2055163
https://docs.microsoft.com/en-us/windows/console/reading-input-buffer-events
https://forum.powerbasic.com/forum/user-to-user-discussions/powerbasic-console-compiler/60919-console-resize-event-in-cc

Seems like a lot of work and I guess @GreyCat didn't went those ways therefore. But there's one thing I recognized: The following screenshot is a resized console before actually pressing any key and the part at the right side gets coloured automatically. If a key gets pressed afterwards, the the right side gets coloured black again. I wonder who does the first colouring and why? If it would be some kind of easier to recognize event to redraw entirely...

![Clipboard01](https://user-images.githubusercontent.com/6223655/55652562-1d7adb80-57ec-11e9-939d-45bb4c8de91f.png)

![Clipboard02](https://user-images.githubusercontent.com/6223655/55652626-616de080-57ec-11e9-9f4e-6eb1d0e545df.png)

How about a different approach entirely? While Windows doesn't support `SIGWINCH`, it's most likely that the user regularly presses keys. Why not use that event to recalculate the size of the console? That's pretty easy to implement and the only downside is that it's pretty ugly to make the console smaller until a key is pressed again.

![Clipboard03](https://user-images.githubusercontent.com/6223655/55652846-025c9b80-57ed-11e9-92d6-308ea366e02a.png)

![Clipboard04](https://user-images.githubusercontent.com/6223655/55652863-0e485d80-57ed-11e9-9e5d-53df7cba173f.png)

![Clipboard05](https://user-images.githubusercontent.com/6223655/55652879-1ef8d380-57ed-11e9-8307-f49bdbfaa1a6.png)
